[package]
name = "raylib-framework-testing"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.2"
raylib = "5.5.1"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["json"] }
